### ISSUE TITLE
Kanshi doesn't apply display position configuration after disabling display

### ISSUE THREAD

**Issue by Jpfonseca** [emersion/kanshi#69] opened 2020-02-18 14:01 UTC
I have been trying to use kanshi to control my displays. 
I expected kanshi to switch between these modes by itself upon realising that eDP-1 was inactive.
My current config is  : 
```
{
	output eDP-1 enable position 0,0
	output "Goldstar wtv" enable mode 1920x1080  position 1366,0    
}
{
        output eDP-1 disable
        output "Goldstar wtv" enable mode 1920x1080  position 0,0
}
```

Upon running `swaymsg -t get_outputs`, **after turning off eDP-1**, I get that the position of the "GoldStar wtv" is 1366,0 instead of 0,0. 

On the wayland-session.log, I get the following messages:
```
2020-02-18 13:52:53 - [swaybg-1.0/main.c:168] Destroying output eDP-1 
applying profile
```
Am I doing something wrong ?  Or is this an expected behaviour?

**Comment by emersion** [comment] 2020-02-18 14:15
Both of these profile blocks specify the same set of outputs. Thus only one of them will be applied.

You need to specify profile blocks with different sets of outputs.

**Comment by Jpfonseca** [comment] 2020-02-18 14:43
> Both of these profile blocks specify the same set of outputs. Thus only one of them will be applied.

I thought I could use 2 profile blocks for the same set of outputs, given their current status(active or inactive), which would allow the configuration of my setup for different scenarios.

**Comment by emersion** [comment] 2020-02-18 14:48
No, this isn't supported yet. The plan is to add support for switching between profiles with `kanshictl switch <profile>`.

Closing as a duplicate of https://github.com/emersion/kanshi/issues/10

**Closed as completed by emersion** 2020-02-18 14:48 UTC
