### ISSUE TITLE
kanshi exits when undocking laptop from two external monitors

### ISSUE THREAD

**Issue by MayeulC** [emersion/kanshi#100] opened 2021-02-09 09:58 UTC
Hello and thank you for this project.

I have a Dell laptop and a WD-15 USB-C dock. It seems that kanshi unexpectedly exits when I run it, plug the dock (with two additional monitors connected), then unplug it:

```
% kanshi
applying profile 'laptop-only'
applying profile output 'Unknown 0x63ED 0x00000000' on connected head 'eDP-1'
running commands for configuration 'laptop-only'
configuration for profile 'laptop-only' applied

# Output Stable, now I plug the dock

applying profile 'INL-homestation2'
applying profile output 'Dell Inc. DELL P2219H F64FYS2' on connected head 'DP-3'
applying profile output 'Unknown 0x63ED 0x00000000' on connected head 'eDP-1'
applying profile 'INL-homestation2'
applying profile output 'Dell Inc. DELL P2219H F64FYS2' on connected head 'DP-3'
applying profile output 'Unknown 0x63ED 0x00000000' on connected head 'eDP-1'
applying profile 'double-inl'
applying profile output 'Dell Inc. DELL P2419HC 4832JQ2' on connected head 'DP-4'
applying profile output 'Dell Inc. DELL P2219H F64FYS2' on connected head 'DP-3'
applying profile output 'Unknown 0x63ED 0x00000000' on connected head 'eDP-1'
applying profile 'double-inl'
applying profile output 'Dell Inc. DELL P2419HC 4832JQ2' on connected head 'DP-4'
applying profile output 'Dell Inc. DELL P2219H F64FYS2' on connected head 'DP-3'
applying profile output 'Unknown 0x63ED 0x00000000' on connected head 'eDP-1'
configuration for profile 'INL-homestation2' cancelled, retrying
configuration for profile 'INL-homestation2' cancelled, retrying
configuration for profile 'double-inl' cancelled, retrying
applying profile 'double-inl'
applying profile output 'Dell Inc. DELL P2419HC 4832JQ2' on connected head 'DP-4'
applying profile output 'Dell Inc. DELL P2219H F64FYS2' on connected head 'DP-3'
applying profile output 'Unknown 0x63ED 0x00000000' on connected head 'eDP-1'
running commands for configuration 'double-inl'
configuration for profile 'double-inl' applied
running commands for configuration 'double-inl'
configuration for profile 'double-inl' applied

# Outputs Stable, now I unplug the dock

applying profile 'INL-homestation1'
applying profile output 'Dell Inc. DELL P2419HC 4832JQ2' on connected head 'DP-4'
applying profile output 'Unknown 0x63ED 0x00000000' on connected head 'eDP-1'
applying profile 'laptop-only'
applying profile output 'Unknown 0x63ED 0x00000000' on connected head 'eDP-1'
wl_display@1: error 1: invalid arguments for zwlr_output_configuration_v1@15.enable_head
% echo $?
0
```

The above always happens when unplugging the laptop from the dock, regardless of when kanshi was launched (before or after docking).

Obviously kanshi becomes a whole less useful if it exits like this. The only suspicious thing I notice is the transient activation of the "INL-homestation1" and 2, which consists of one of the two external monitors. It might be a race condition when one of those disappear, kanshi tries to set the other up according to a profile, but it's already gone? **It doesn't happen when only one external monitor is connected**, which suggest it is related.

Reproductibility is extremelly good FWIW, it happens every time, with the exact same lines.

Here are the relevant lines in the kanshi config:

```
## Work profiles
profile laptop-only {
	output "Unknown 0x63ED 0x00000000" mode 1920x1080 position 0,0 enable
}

profile INL-workstation {
	output "Dell Inc. DELL E2218HN 33G587CKC67I" mode 1920x1080 position 0,0
	output "Unknown 0x63ED 0x00000000" mode 1920x1080 position 1920,360
}

profile INL-homestation1 {
	output "Unknown 0x63ED 0x00000000" mode 1920x1080 position 0,0
	output "Dell Inc. DELL P2419HC 4832JQ2" mode 1920x1080 position 1920,0
}

profile INL-homestation2 {
	output "Dell Inc. DELL P2219H F64FYS2" mode 1920x1080 position 0,0
	output "Unknown 0x63ED 0x00000000" mode 1920x1080 position 1920,0
}

profile double-inl {
	output "Dell Inc. DELL P2419HC 4832JQ2" position 0,0 mode 1920x1080 transform 90
	output "Dell Inc. DELL P2219H F64FYS2" position 1080,416
	output "Unknown 0x63ED 0x00000000" disable
}

```

**Comment by emersion** [comment] 2021-02-09 10:11
Duplicate of https://github.com/emersion/kanshi/issues/99

**Closed as completed by emersion** 2021-02-09 10:11 UTC

**Comment by MayeulC** [comment] 2021-02-09 10:15
You beat me to it by 3 minutes, sorry about that.
