### ISSUE TITLE
kanshi crashes: invalid arguments for zwlr_output_configuration_v1@9.enable_head

### ISSUE THREAD

**Issue by tbm** [emersion/kanshi#61] opened 2019-12-24 18:38 UTC
kanshi crashes with:

```
wl_display@1: error 1: invalid arguments for zwlr_output_configuration_v1@9.enable_head
```

I assume this is another issue that will be fixed by swaywm/wlroots#1765 but I wanted to document the issue.

**Comment by emersion** [comment] 2019-12-24 20:15
Duplicate of https://github.com/emersion/kanshi/issues/55

**Closed as completed by emersion** 2019-12-24 20:15 UTC
