### ISSUE TITLE
Support lid closure

### ISSUE THREAD

**Issue by tbm** [emersion/kanshi#56] opened 2019-12-04 14:48 UTC
As far as I can tell, kanshi doesn't support a config based on whether my laptop lid is open or closed.

I'd like to have a different configuration between:

* Laptop open and external monitor
* Laptop closed and external monitor

**Comment by emersion** [comment] 2019-12-04 14:49
Kanshi doesn't have access to this information.

**Comment by tbm** [comment] 2019-12-04 14:53
Is there no notify mechanism you can plug into?

If not, what would the solution be?  A script that calls the right swaymsg calls on lid closure?  But if a script can get those notifications, why can't kanshi.

(Sorry, I'm not familiar with the low-level notification available)

**Comment by Emantor** [comment] 2019-12-04 18:15
Sway supports bindswitch for the lid event, you can disable your output on close and reenable on open.

**Comment by tbm** [comment] 2019-12-04 18:18
@Emantor 
> Sway supports bindswitch for the lid event, you can disable your output on close and reenable on open.

Yeah, that's what I originally used but I had [some problems](https://github.com/swaywm/sway/issues/4745) with that approach and was told to use kanshi. While that resolves my original problem, it doesn't do everything I wanted to do.

**Comment by emersion** [comment] 2019-12-04 18:27
FWIW, https://github.com/emersion/kanshi/issues/10 plans to allow switching between two profiles. This could probably be used to have both a "lid closed" and a "lid opened" profile.

**Comment by tbm** [comment] 2019-12-04 18:29
And then I would need a systemd script to call kanshictl on lid closure/open?

I suppose that would work. I wish there was a simpler, more integrated solution though.

**Comment by emersion** [comment] 2019-12-04 18:31
No need for systemd, you could do this instead in the Sway config:

```
bindswitch --locked lid:on exec kanshictl switch lid-opened
bindswitch --locked lid:off exec kanshictl switch lid-closed
```

**Comment by tbm** [comment] 2019-12-04 18:38
Ohh yes, I didn't think that far.

yeah, that would be nice.  Well, feel free to close this issue if you want, or maybe leave it open until #10 is addressed and then this one can be used as a documentation issue to describe the scenario (i.e. mention the two sway config lines).

Thanks again, both @emersion and @Emantor

**Comment by palb91** [comment] 2019-12-19 22:01
> ```
> bindswitch --locked lid:on exec kanshictl switch lid-opened
> bindswitch --locked lid:off exec kanshictl switch lid-closed
> ```

Hi! How does it works with several configuration in kanshi ? I have 3 main profiles (Home, Work, laptop only) and for both Home and Work I would like to be able to enable/disable the laptop screen on open/close event. It seems that your solution would load a specific profile which would lead to an unexpected behavior if the profile doesn't fit the configuration.

I can see a possibility:
```
bindswitch --locked lid:on exec kanshictl switch home-nolid || kanshictl switch work-nolid
bindswitch --locked lid:off exec kanshictl switch home || kanshictl switch work
```
but for people using more profiles it would become hard to maintain that (And I hope that `exec false || true` will return true in sway).

I hope I'm missing something that could simplify it :/

*(note: from the sway(5) `lid:on` means laptop closed)*

**Comment by palb91** [comment] 2019-12-19 22:14
Also, when I was on i3 with autorandr running with an udev rule, I used a block script that check the content of `/proc/acpi/button/lid/LID0/state` to load either **X** or **X_nolid** (all my profiles had a _nolid equivalent).

I don't know how standard this path is and if you can rely on it but it doesn't hurt to ask ;) Would it be possible to add this kind of check in kanshi? Or allow the user to add a block rule, causing kanshi to load the next profile corresponding to the current configuration ?

**Comment by emersion** [comment] 2019-12-20 13:05
>Would it be possible to add this kind of check in kanshi?

Probably not.

My plan was to allow to specify multiple profiles with the same name, and choose the one that matches the current configuration.

**Comment by palb91** [comment] 2019-12-20 15:58
Exactly the kind of something I hoped I missed ^^
That would be a great behavior!
I guess the flag ``--reload`` will be mandatory for ``bindswitch``

**Comment by eoli3n** [comment] 2020-01-12 08:33
I use a videoprojector, which is always connected, but i want to be able to switch if it is power off/on.
That's pretty similar to lid behaviour, how can i do that ?

**Comment by emersion** [comment] 2020-01-12 11:12
>I use a videoprojector, which is always connected, but i want to be able to switch if it is power off/on.
That's pretty similar to lid behaviour, how can i do that ?

That's unrelated to lid behaviour: the projector will appear as disconnected while switched off.

**Comment by emersion** [comment] 2020-03-29 15:15
Closing because lid closure support won't be added directly to kanshi. See the comments above.

**Closed as completed by emersion** 2020-03-29 15:15 UTC

**Comment by ghost** [comment] 2021-05-01 12:54
Came across this issue recently. Was trying to fix an issue where kanshi with those conditions:
* laptop docked
* external display connected to dock
* laptop woken from sleep using dock's power button

... wouldn't start the external display (I would need to take out the laptop out of the dock, open the lid, dock the laptop again, close the lid, and then the display would work)

This was happening because I forgot I applied the instructions from Sway's wiki for [Clamshell Mode](https://github.com/swaywm/sway/wiki#clamshell-mode) before I even discovered kanshi existed. The (non-working) instructions ofcourse are:
```
#THIS IS WRONG DONT PASTE THIS
set $laptop <laptop_output_identifier>
bindswitch --reload --locked lid:on output $laptop disable
bindswitch --reload --locked lid:off output $laptop enable
```

What fixed it for me is switching the above lines [to what emersion posted above](https://github.com/emersion/kanshi/issues/56#issuecomment-561779205)

Now pressing the power button on the dock after putting the laptop to sleep starts the external & dock-connected monitor normally. I don't have to re-dock anymore.
